"""
This module contains constant values used across the solar calculator application.
"""

# Power generated by one solar panel in kilowatts
PANEL_POWER_KW = 0.61

# Efficiency of the system (adjusted for losses)
SYSTEM_EFFICIENCY = 0.78

# Area occupied by one panel in square meters
PANEL_AREA_M2 = 2.7

# CO2 saved per kWh in kilograms
CO2_SAVED_PER_KWH = 0.5

# Trees offset per 10 kg of CO2 saved
TREE_FACTOR = 0.8

# Value-added tax rate (IVA)
TAX_RATE = 0.12

# Expected system lifetime in years
SYSTEM_LIFETIME_YEARS = 25

# Cost per kilowatt of installed capacity in local currency
COST_PER_KW = 7500

# Energy price per kWh
PRICE_PER_KWH = 1.8